<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Itdear.Aplicacion.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Itdear.Dominio.Core\Itdear.Dominio.Core.csproj" />
    <ProjectReference Include="..\Itdear.Infraestructura.Transversal\Itdear.Infraestructura.Transversal.csproj" />
  </ItemGroup>

</Project>
