<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EfCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\1.1 Transversal\Itdear.Infraestructura.Datos.Core\Itdear.Infraestructura.Datos.Core.csproj" />
    <ProjectReference Include="..\..\1.4 Dominio\ECM.Dominio\ECM.Dominio.csproj" />
  </ItemGroup>

</Project>
