<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="$(EfCoreVersion)" />
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="$(JwtVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\1.1 Transversal\Itdear.Aplicacion.Core\Itdear.Aplicacion.Core.csproj" />
    <ProjectReference Include="..\..\..\1.1 Transversal\Itdear.Infraestructura.Seguridad\Itdear.Infraestructura.Seguridad.csproj" />
    <ProjectReference Include="..\..\..\1.1 Transversal\Itdear.Infraestructura.Transversal\Itdear.Infraestructura.Transversal.csproj" />
    <ProjectReference Include="..\ECM.Aplicacion.Servicios.Interfaz\ECM.Aplicacion.Servicios.Interfaz.csproj" />
  </ItemGroup>

</Project>
