<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\1.3.2 DTO\ECM.Aplicacion.DTO\ECM.Aplicacion.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Itdear.Aplicacion.Core">
      <HintPath>..\..\..\..\Packages\Itdear.Aplicacion.Core.1.0.0\Itdear.Aplicacion.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
